# Generated by Django 5.1.1 on 2024-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intradata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('marketCap', models.CharField(max_length=50, null=True)),
                ('initialPrice', models.FloatField()),
                ('maximaOfGap', models.FloatField()),
                ('minimaOfGap', models.FloatField()),
                ('gap', models.FloatField()),
                ('finalPrice', models.FloatField()),
                ('finalGain', models.FloatField()),
                ('dayHigh', models.FloatField()),
                ('dayLow', models.FloatField()),
                ('maximaOfGap1', models.FloatField(null=True)),
                ('minimaOfGap1', models.FloatField(null=True)),
                ('gap1', models.FloatField(null=True)),
                ('finalPrice1', models.FloatField(null=True)),
                ('dayHigh1', models.FloatField(null=True)),
                ('dayLow1', models.FloatField(null=True)),
                ('maximaOfGap2', models.FloatField(null=True)),
                ('minimaOfGap2', models.FloatField(null=True)),
                ('gap2', models.FloatField(null=True)),
                ('finalPrice2', models.FloatField(null=True)),
                ('dayHigh2', models.FloatField(null=True)),
                ('dayLow2', models.FloatField(null=True)),
            ],
        ),
    ]
