# Generated by Django 5.1.1 on 2024-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intradayData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intradata',
            name='companyName',
            field=models.CharField(max_length=100),
        ),
    ]
