# Generated by Django 5.1.1 on 2024-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intradayData', '0004_intradata_finalgain2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intradata',
            name='marketCap',
            field=models.FloatField(null=True),
        ),
    ]
