# Generated by Django 5.1.1 on 2024-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intradayData', '0005_alter_intradata_marketcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intradata',
            name='marketCap',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
